### PR TITLE
Add pin definitions to target.json

### PR DESCRIPTION
**Pull request by bremoran**
Pin definitions necessary for https://github.com/ARMmbed/mbed-hal/pull/23

### CODE REVIEW

**Comment by sg-** [comment]
Only comment is that with a change like this there should be a target-frdm-k64 which has the definitions such that we dont copy paste in both armcc, gcc, iar , etc and instead inherit from a board then add toolchain support.

**Comment by bremoran** [comment]
@sg- I also considered this, but there are problems with multiple inheritance that we don't want yotta to have to solve.

**Comment by AlessandroA** [comment]
@sg- , @bremoran I was also considering this (I'm moving `cmsis_nvic.{c,h}` to `cmsis-core`); what problems do we have exactly with multiple inheritance?

**Comment by bogdanm** [comment]
+1, but I'm also interested in the multiple inheritance issue. Seems to be something quite useful in this context. I can imagine that the issues would have to do with classic multiple inheritance problems, but we can probably make this work in practice.

**Comment by autopulated** [comment]
leaving aside possible multiple inheritance implementations (for now) – this looks to me to be good to merge?

**Comment by bogdanm** [comment]
Yup.

**Comment by sg-** [comment]
I've been trying multiple inheritance and that fails and so does "dependencies" - This seems to need a yotta change in the way targets are handled.

**Comment by autopulated** [comment]
yeah targets don't currently support multiple inheritance.

**Pull request merged**
