### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by sg-**
Remove depreciated mbed Enabled logo

### CODE REVIEW

**Comment by 0xc0170** [comment]
Can we do something with the picture, the padding is large.

[rendered](https://github.com/ARMmbed/target-frdm-k64f-armcc/blob/sg--patch-1/readme.md)

**Comment by sg-** [comment]
its the exact same as xxx-xxx-gcc

**Comment by 0xc0170** [comment]
@sg- Agree, just asking if we can improve, not holding this PR

**Comment by autopulated** [comment]
I cropped the image, if you can upload it to the mbed-media s3, then I'll update the image link:

k64f

(I'm not sure if it's OK to hotlink stuff from github's comment image upload hosting?)

**Pull request merged**
